### ISSUE TITLE
This repository is empty.

### ISSUE THREAD

**Issue by victorbnl** [Fomys/messages#1]
<p></p>

<p align="center">
<img src="https://user-images.githubusercontent.com/39555268/116162616-7466ec80-a6f6-11eb-91ea-3d7c35b9d341.png">
</p>

<h3 align="center">This repository is empty.</h3>

<p align="center">
Care to check out the <a href="https://youtube.com/GitHub">GitHub Channel on YouTube</a> while you wait?
</p>

<p></p>

**Comment by Fomys** [comment]
You can check the date of the commit, it was before your issue!

**Comment by victorbnl** [comment]
How the hell, yesterday evening it showed as an empty repository, when I made this issue

**Comment by victorbnl** [comment]
But it can make us think about the sense of life, while you can say files are present on this repository, you can also say that files aren't here. I mean, is the repository half full or half empty? On the point of view of .gitignore, files in it aren't listed on the repository, but further, I think your repo doesn't take the whole space of the disk of GitHub's server.
